logFilters:
  - code: YN0002
    level: discard
  - code: YN0013
    level: discard
  - code: YN0018
    level: discard
  - code: YN0060
    level: discard
  - code: YN0076
    level: discard

enableTelemetry: false
preferInteractive: false
